openapi: 3.0.0
info:
  title: Kinesis Video Streams API
  version: 1.0.0
  description: API for interacting with Amazon Kinesis Video Streams
servers:
  - url: 'https://kinesisvideo.{region}.amazonaws.com'
    description: Main server for Kinesis Video Streams API

paths:
  /createStream:
    post:
      summary: Creates a new Kinesis video stream
      operationId: createStream
      tags:
        - Streams
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateStreamRequest'
      responses:
        '200':
          description: Stream created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateStreamResponse'

  /describeStream:
    post:
      summary: Describes the specified Kinesis video stream
      operationId: describeStream
      tags:
        - Streams
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DescribeStreamRequest'
      responses:
        '200':
          description: Stream description retrieved
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DescribeStreamResponse'

components:
  schemas:
    CreateStreamRequest:
      type: object
      properties:
        StreamName:
          type: string
        DataRetentionInHours:
          type: integer
    CreateStreamResponse:
      type: object
      properties:
        StreamARN:
          type: string

    DescribeStreamRequest:
      type: object
      properties:
        StreamName:
          type: string
    DescribeStreamResponse:
      type: object
      properties:
        StreamInfo:
          $ref: '#/components/schemas/StreamInfo'

    StreamInfo:
      type: object
      properties:
        StreamName:
          type: string
        StreamARN:
          type: string
        MediaType:
          type: string
        DataRetentionInHours:
          type: integer
