openapi: 3.0.0
info:
  title: Stolen Vehicle Alert API
  version: 1.0.0
  description: API for managing stolen vehicles, including tracking and control.

paths:
  /vehicle/stolen:
    post:
      summary: Set Stolen Vehicle Mode
      description: Endpoint to activate Stolen Vehicle Mode. Requires agent authorization.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/StolenVehicleModeRequest'
      responses:
        '200':
          description: Stolen Vehicle Mode activated successfully.
        '401':
          description: Unauthorized access.

  /vehicle/gnss:
    post:
      summary: Post GNSS Information
      description: Endpoint for the vehicle to post its GNSS information every 60 seconds.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GnssInformation'
      responses:
        '200':
          description: GNSS information received successfully.

  /vehicle/control:
    post:
      summary: Send Vehicle Control Commands
      description: Endpoint to send commands to the stolen vehicle, like slowing down the engine or preventing ignition start.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/VehicleControlCommand'
      responses:
        '200':
          description: Command sent successfully.

components:
  schemas:
    StolenVehicleModeRequest:
      type: object
      properties:
        vehicleId:
          type: string
        agentAuthorizationKey:
          type: string

    GnssInformation:
      type: object
      properties:
        vehicleId:
          type: string
        latitude:
          type: number
          format: float
        longitude:
          type: number
          format: float
        heading:
          type: number
          format: float
          description: Directional heading in degrees.
        gpsLockType:
          type: string
          enum: [none, 2D, 3D]
        timestamp:
          type: string
          format: date-time

    VehicleControlCommand:
      type: object
      properties:
        vehicleId:
          type: string
        commandType:
          type: string
          enum: [slowDownEngine, preventIgnitionStart]

