openapi: 3.0.0
info:
  title: Extended Connected API
  version: no version
paths: {}
components:
  schemas:
    # Existing schema definitions from the first specification
    TelemetryData:
      type: object
      properties:
        location:
          type: object
          properties:
            latitude:
              type: number
              format: double
            longitude:
              type: number
              format: double
        speed:
          type: number
          format: double
        engineStatus:
          type: string
    
    InsightsData:
      type: object
      properties:
        fuelEfficiency:
          type: number
          format: double
        tirePressure:
          type: array
          items:
            type: number

    VehicleCommand:
      type: object
      properties:
        commandType:
          type: string
          enum: [lock, unlock, startEngine, stopEngine]
        parameters:
          type: object

    CommandResponse:
      type: object
      properties:
        status:
          type: string
          enum: [success, failure]
        message:
          type: string

    # New schema definitions from the second specification
    RemoteClimateRequest:
      type: object
      properties:
        command:
          $ref: '#/components/schemas/RemoteClimateRequest.CommandEnum'
        interiorTemperature:
          description: int32 duration = 2; // Duration
          type: integer
          format: int32
        fanSpeed:
          type: integer
          format: int32
        termperatureUOM:
          $ref: '#/components/schemas/RemoteClimateRequest.TemperatureEnum'
        targetTemp:
          type: integer
          format: int32
        timeoutAfterTemp:
          type: integer
          format: int32
        preTripTimeout:
          type: integer
          format: int32
    RemoteClimateRequest.CommandEnum:
      type: string
      enum:
        - "ON"
        - "OFF"
    RemoteClimateRequest.TemperatureEnum:
      type: string
      enum:
        - Celsius
        - Fahrenheit
    RemoteDoorRequest:
      type: object
      properties:
        command:
          $ref: '#/components/schemas/RemoteDoorRequest.CommandEnum'
    RemoteDoorRequest.CommandEnum:
      type: string
      enum:
        - LOCK_ALL_DOORS
        - UNLOCK_DRIVER_DOOR
        - UNLOCK_ALL_DOORS
        - OPEN_LIFTGATE
        - OPEN_HOOD
        - UNLOCK_TRUNK
        - CLOSE_LIFTGATE

    RemoteEngineRequest:
      type: object
      properties:
        command:
          $ref: '#/components/schemas/RemoteEngineRequest.CommandEnum'
        duration:
          type: integer
          format: int32
    RemoteEngineRequest.CommandEnum:
      type: string
      enum:
        - START
        - STOP

    RemoteHornAndLightsRequest:
      description: |-
        message CancelRequest {
          bytes serviceRequestId = 1;
        }
        This message represents RemoteHornAndLights Operation of the vehicle.
        # Example message details...
      type: object
      properties:
        command:
          $ref: '#/components/schemas/RemoteHornAndLightsRequest.CommandEnum'
        duration:
          type: integer
          format: int32
    RemoteHornAndLightsRequest.CommandEnum:
      type: string
      enum:
        - HORN_AND_LIGHTS

    RemoteOperationRequest:
      description: |-
        import public "Global_Uconnect_Control.proto";
        import public "Global_Uconnect_VehicleInfo.proto";
        # Example message details...
      type: object
      properties:
        action:
          $ref: '#/components/schemas/RemoteOperationRequest.ActionEnum'
        serviceRequestId:
          type: string
          format: binary
      oneOf:
        # oneOf conditions...
    RemoteOperationRequest.ActionEnum:
      type: string
      enum:
        - NO_ACTION
        - SUBSCRIBE

    RemoteOperationResponse:
      description: |-
        This message represents Response to Remote Operation of the vehicle.
        # Example message details...
      type: object
      properties:
        response:
          $ref: '#/components/schemas/RemoteOperationResponse.ResponseEnum'
        serviceRequestId:
          type: string
          format: binary
        isTransient:
          type: boolean
        failureReasonCode:
          type: integer
          format: int32
    RemoteOperationResponse.ResponseEnum:
      type: string
      enum:
        # Enum values...
    
    RemoteWindowRequest:
      type: object
      properties:
        command:
          $ref: '#/components/schemas/RemoteWindowRequest.CommandEnum'
    RemoteWindowRequest.CommandEnum:
      type: string
      enum:
        - OPEN
        - PARTIAL
        - CLOSE
