openapi: 3.0.0
info:
  title: Digital Key Service API
  version: 1.0.0
  description: API for managing digital keys for vehicles, following Connected Car Consortium standards.

paths:
  /digitalkey/generate:
    post:
      summary: Generate Digital Key
      description: Endpoint to generate an encrypted digital key for a vehicle.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DigitalKeyRequest'
      responses:
        '200':
          description: Digital key generated successfully.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DigitalKeyResponse'
        '401':
          description: Unauthorized access.

  /digitalkey/invalidate:
    post:
      summary: Invalidate Digital Key
      description: Endpoint to invalidate an existing digital key.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/InvalidateKeyRequest'
      responses:
        '200':
          description: Digital key invalidated successfully.
        '401':
          description: Unauthorized access.

  /digitalkey/send:
    post:
      summary: Send Digital Key to Vehicle
      description: Endpoint to send the digital key to the vehicle via a secure pre-signed AWS S3 URL.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SendKeyRequest'
      responses:
        '200':
          description: Digital key sent successfully.
        '401':
          description: Unauthorized access.

components:
  schemas:
    DigitalKeyRequest:
      type: object
      properties:
        authorizationKey:
          type: string
        vehicleId:
          type: string

    DigitalKeyResponse:
      type: object
      properties:
        digitalKey:
          type: string
          format: byte
          description: Encrypted digital key for the vehicle.

    InvalidateKeyRequest:
      type: object
      properties:
        digitalKey:
          type: string
          format: byte
        vehicleId:
          type: string

    SendKeyRequest:
      type: object
      properties:
        digitalKey:
          type: string
          format: byte
        vehicleId:
          type: string
        s3PresignedUrl:
          type: string
          format: uri
          description: Secure pre-signed AWS S3 URL for sending the digital key.

