openapi: 3.0.0
info:
  title: Geo and Speed Fencing API
  version: 1.0.0
  description: API for setting and monitoring geo, speed, and time boundaries for vehicles.

paths:
  /fence/speed:
    post:
      summary: Set Speed Boundary
      description: Endpoint to set speed boundaries for a vehicle.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SpeedBoundary'
      responses:
        '200':
          description: Speed boundary set successfully.

  /fence/geo:
    post:
      summary: Set Geo Boundary
      description: Endpoint to set geo boundaries for a vehicle.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GeoBoundary'
      responses:
        '200':
          description: Geo boundary set successfully.

  /fence/time:
    post:
      summary: Set Time Boundary
      description: Endpoint to set time boundaries for a vehicle.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TimeBoundary'
      responses:
        '200':
          description: Time boundary set successfully.

  /alerts:
    post:
      summary: Receive Alert
      description: Endpoint for receiving alerts when a vehicle exceeds set boundaries.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Alert'
      responses:
        '200':
          description: Alert received successfully.

components:
  schemas:
    SpeedBoundary:
      type: object
      properties:
        vehicleId:
          type: string
        maxSpeed:
          type: number
          format: float
          description: Maximum speed in km/h.

    GeoBoundary:
      type: object
      properties:
        vehicleId:
          type: string
        latitude:
          type: number
          format: float
        longitude:
          type: number
          format: float
        radius:
          type: number
          format: float
          description: Radius in meters.

    TimeBoundary:
      type: object
      properties:
        vehicleId:
          type: string
        startTime:
          type: string
          format: date-time
        endTime:
          type: string
          format: date-time

    Alert:
      type: object
      properties:
        vehicleId:
          type: string
        type:
          type: string
          enum: [speed, geo, time]
        details:
          type: object

