openapi: 3.0.0
info:
  title: Extended Connected API
  version: no version
paths:
  /vehicles/{vehicleId}/telemetry:
    get:
      summary: Get telemetry data
      operationId: getTelemetry
      parameters:
        - name: vehicleId
          in: path
          required: true
          description: Unique identifier of the vehicle
          schema:
            type: string
      responses:
        '200':
          description: Telemetry data retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TelemetryData'

  /vehicles/{vehicleId}/insights:
    get:
      summary: Get insights from S3 bucket
      operationId: getInsights
      parameters:
        - name: vehicleId
          in: path
          required: true
          description: Unique identifier of the vehicle
          schema:
            type: string
      responses:
        '200':
          description: Insights data retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InsightsData'

  /vehicles/{vehicleId}/commands:
    post:
      summary: Execute remote commands on the vehicle
      operationId: executeCommand
      parameters:
        - name: vehicleId
          in: path
          required: true
          description: Unique identifier of the vehicle
          schema:
            type: string
      requestBody:
        description: Command to be executed
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/VehicleCommand'
      responses:
        '200':
          description: Command executed successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CommandResponse'
/vehicles/{vehicleId}/remoteClimate:
    post:
      summary: Send remote climate control command
      operationId: sendRemoteClimateCommand
      parameters:
        - name: vehicleId
          in: path
          required: true
          description: Unique identifier of the vehicle
          schema:
            type: string
      requestBody:
        description: Remote climate control request
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RemoteClimateRequest'
      responses:
        '200':
          description: Remote climate control command sent successfully

/vehicles/{vehicleId}/remoteDoor:
    post:
      summary: Send remote door control command
      operationId: sendRemoteDoorCommand
      parameters:
        - name: vehicleId
          in: path
          required: true
          description: Unique identifier of the vehicle
          schema:
            type: string
      requestBody:
        description: Remote door control request
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RemoteDoorRequest'
      responses:
        '200':
          description: Remote door control command sent successfully

 /vehicles/{vehicleId}/remoteEngine:
    post:
      summary: Send remote engine control command
      operationId: sendRemoteEngineCommand
      parameters:
        - name: vehicleId
          in: path
          required: true
          description: Unique identifier of the vehicle
          schema:
            type: string
      requestBody:
        description: Remote engine control request
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RemoteEngineRequest'
      responses:
        '200':
          description: Remote engine control command sent successfully

  /vehicles/{vehicleId}/remoteHornAndLights:
    post:
      summary: Send remote horn and lights control command
      operationId: sendRemoteHornAndLightsCommand
      parameters:
        - name: vehicleId
          in: path
          required: true
          description: Unique identifier of the vehicle
          schema:
            type: string
      requestBody:
        description: Remote horn and lights control request
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RemoteHornAndLightsRequest'
      responses:
        '200':
          description: Remote horn and lights control command sent successfully

  /vehicles/{vehicleId}/remoteOperation:
    post:
      summary: Send remote operation request
      operationId: sendRemoteOperationRequest
      parameters:
        - name: vehicleId
          in: path
          required: true
          description: Unique identifier of the vehicle
          schema:
            type: string
      requestBody:
        description: Remote operation request
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RemoteOperationRequest'
      responses:
        '200':
          description: Remote operation request sent successfully

  /vehicles/{vehicleId}/remoteWindow:
    post:
      summary: Send remote window control command
      operationId: sendRemoteWindowCommand
      parameters:
        - name: vehicleId
          in: path
          required: true
          description: Unique identifier of the vehicle
          schema:
            type: string
      requestBody:
        description: Remote window control request
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RemoteWindowRequest'
      responses:
        '200':
          description: Remote window control command sent successfully
components:
  schemas:
    # Existing schema definitions from the first specification
    TelemetryData:
      type: object
      properties:
        location:
          type: object
          properties:
            latitude:
              type: number
              format: double
            longitude:
              type: number
              format: double
        speed:
          type: number
          format: double
        engineStatus:
          type: string
    
    InsightsData:
      type: object
      properties:
        fuelEfficiency:
          type: number
          format: double
        tirePressure:
          type: array
          items:
            type: number

    VehicleCommand:
      type: object
      properties:
        commandType:
          type: string
          enum: [lock, unlock, startEngine, stopEngine]
        parameters:
          type: object

    CommandResponse:
      type: object
      properties:
        status:
          type: string
          enum: [success, failure]
        message:
          type: string

    # New schema definitions from the second specification
    RemoteClimateRequest:
      type: object
      properties:
        command:
          $ref: '#/components/schemas/RemoteClimateRequest.CommandEnum'
        interiorTemperature:
          description: int32 duration = 2; // Duration
          type: integer
          format: int32
        fanSpeed:
          type: integer
          format: int32
        termperatureUOM:
          $ref: '#/components/schemas/RemoteClimateRequest.TemperatureEnum'
        targetTemp:
          type: integer
          format: int32
        timeoutAfterTemp:
          type: integer
          format: int32
        preTripTimeout:
          type: integer
          format: int32
    RemoteClimateRequest.CommandEnum:
      type: string
      enum:
        - "ON"
        - "OFF"
    RemoteClimateRequest.TemperatureEnum:
      type: string
      enum:
        - Celsius
        - Fahrenheit
    RemoteDoorRequest:
      type: object
      properties:
        command:
          $ref: '#/components/schemas/RemoteDoorRequest.CommandEnum'
    RemoteDoorRequest.CommandEnum:
      type: string
      enum:
        - LOCK_ALL_DOORS
        - UNLOCK_DRIVER_DOOR
        - UNLOCK_ALL_DOORS
        - OPEN_LIFTGATE
        - OPEN_HOOD
        - UNLOCK_TRUNK
        - CLOSE_LIFTGATE

    RemoteEngineRequest:
      type: object
      properties:
        command:
          $ref: '#/components/schemas/RemoteEngineRequest.CommandEnum'
        duration:
          type: integer
          format: int32
    RemoteEngineRequest.CommandEnum:
      type: string
      enum:
        - START
        - STOP

    RemoteHornAndLightsRequest:
      description: |-
        message CancelRequest {
          bytes serviceRequestId = 1;
        }
        This message represents RemoteHornAndLights Operation of the vehicle.
        # Example message details...
      type: object
      properties:
        command:
          $ref: '#/components/schemas/RemoteHornAndLightsRequest.CommandEnum'
        duration:
          type: integer
          format: int32
    RemoteHornAndLightsRequest.CommandEnum:
      type: string
      enum:
        - HORN_AND_LIGHTS

    RemoteOperationRequest:
      description: |-
        import public "Global_Uconnect_Control.proto";
        import public "Global_Uconnect_VehicleInfo.proto";
        # Example message details...
      type: object
      properties:
        action:
          $ref: '#/components/schemas/RemoteOperationRequest.ActionEnum'
        serviceRequestId:
          type: string
          format: binary
      oneOf:
        # oneOf conditions...
    RemoteOperationRequest.ActionEnum:
      type: string
      enum:
        - NO_ACTION
        - SUBSCRIBE

    RemoteOperationResponse:
      description: |-
        This message represents Response to Remote Operation of the vehicle.
        # Example message details...
      type: object
      properties:
        response:
          $ref: '#/components/schemas/RemoteOperationResponse.ResponseEnum'
        serviceRequestId:
          type: string
          format: binary
        isTransient:
          type: boolean
        failureReasonCode:
          type: integer
          format: int32
    RemoteOperationResponse.ResponseEnum:
      type: string
      enum:
        # Enum values...
    
    RemoteWindowRequest:
      type: object
      properties:
        command:
          $ref: '#/components/schemas/RemoteWindowRequest.CommandEnum'
    RemoteWindowRequest.CommandEnum:
      type: string
      enum:
        - OPEN
        - PARTIAL
        - CLOSE
