openapi: 3.0.0
info:
  title: Extended Vehicle APIs
  version: no version
paths:
  /vehicles/{vehicleId}/telemetry:
    get:
      summary: Get telemetry data
      operationId: getTelemetry
      parameters:
        - name: vehicleId
          in: path
          required: true
          description: Unique identifier of the vehicle
          schema:
            type: string
      responses:
        '200':
          description: Telemetry data retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TelemetryData'
  /vehicles/{vehicleId}/insights:
    get:
      summary: Get insights from S3 bucket
      operationId: getInsights
      parameters:
        - name: vehicleId
          in: path
          required: true
          description: Unique identifier of the vehicle
          schema:
            type: string
      responses:
        '200':
          description: Insights data retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InsightsData'
components:
  schemas:
    TelemetryData:
      type: object
      properties:
        location:
          type: object
          properties:
            latitude:
              type: number
              format: double
            longitude:
              type: number
              format: double
        speed:
          type: number
          format: double
        engineStatus:
          type: string
        fuelLevel:
          type: number
          format: double
        batteryVoltage:
          type: number
          format: double
        coolantTemperature:
          type: number
          format: double
        odometer:
          type: number
          format: double
        diagnosticTroubleCodes:
          type: array
          items:
            type: string

    InsightsData:
      type: object
      properties:
        fuelEfficiency:
          type: number
          format: double
        tirePressure:
          type: array
          items:
            type: number
        averageSpeed:
          type: number
          format: double
        harshAccelerationEvents:
          type: integer
        harshBrakingEvents:
          type: integer
        idleTime:
          type: number
          format: double
