openapi: 3.0.0
info:
  title: Vehicle Control and Monitoring API
  version: 1.0.0
  description: API for monitoring and controlling various vehicle attributes.

paths:
  /vehicle/status:
    post:
      summary: Update Vehicle Status
      description: Endpoint for posting updates to various vehicle attributes.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/VehicleStatusUpdate'
      responses:
        '200':
          description: Vehicle status updated successfully.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VehicleStatusResponse'
        '400':
          description: Invalid request.

  /vehicle/commands:
    post:
      summary: Send Command to Vehicle
      description: Endpoint for sending commands to change vehicle states.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/VehicleCommand'
      responses:
        '200':
          description: Command sent successfully.
        '400':
          description: Invalid command.

components:
  schemas:
    VehicleStatusUpdate:
      type: object
      properties:
        ignitionStatus:
          type: string
          enum:
            - Off
            - Accessory
            - On
            - Start
        doorLockStatus:
          type: object
          properties:
            frontLeft:
              type: boolean
            frontRight:
              type: boolean
            rearLeft:
              type: boolean
            rearRight:
              type: boolean
        trunkLockStatus:
          type: boolean
        batteryLevel:
          type: number
          format: float
        fuelLevel:
          type: number
          format: float
        dtcCodes:
          type: array
          items:
            type: string
        windowPosition:
          type: object
          properties:
            frontLeft:
              type: number
            frontRight:
              type: number
            rearLeft:
              type: number
            rearRight:
              type: number

    VehicleStatusResponse:
      type: object
      properties:
        status:
          type: string
          description: Status message of the update.

    VehicleCommand:
      type: object
      properties:
        commandType:
          type: string
          enum: [lockDoors, unlockDoors, startEngine, stopEngine, etc.]
        parameters:
          type: object

