apiVersion: backstage.io/v1alpha1
kind: component
metadata:
  name: aws-iot-fleetwise-evbatterymonitoring
  annotations:
    github.com/project-slug: jamesenki/aws-iot-fleetwise-evbatterymonitoring
spec:
  type: service
  lifecycle: unknown
  owner: aws
