# https://docs.aws.amazon.com/proton/latest/userguide/ag-infrastructure-tmp-files-codebuild.html

schema:
  format:
    openapi: "3.0.0"
  service_input_type: "FleetWiseEVBatteryMonitoring"
  pipeline_input_type: "PipelineInputs"
  types:
    FleetWiseEVBatteryMonitoring:
      type: object
      description: "Input properties for FleetWise EV Battery Monitoring"
      properties:
        a_number:
          title: "A number option"
          type: number
          description: "A number with a min and max"
          default: 80
          minimum: 0
          maximum: 65535
    PipelineInputs:
      type: object
      description: "Pipeline input properties"
      properties:
        unit_test_command:         # parameter
          type: string
          description: "The command to run to unit test the application code"
          default: "echo 'add your unit test command here'"
          minLength: 1
          maxLength: 200
